name: Continuous Integration
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v1
        
    - uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Begin Sonarcloud scanner
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $url = "https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.10.0.19059/sonar-scanner-msbuild-4.10.0.19059-net46.zip"
        Invoke-WebRequest $url -Outfile C:\sonar.zip
        Expand-Archive -DestinationPath C:\sonar -Path C:\sonar.zip
        & C:\sonar\SonarScanner.MSBuild.exe begin /k:ArwynFr_AspectNetSharp /o:arwynfr /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Compile solution
      run: msbuild AspectNetSharp.sln
      
    - name: End Sonarcloud scanner
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        & C:\sonar\SonarScanner.MSBuild.exe end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

