name: Continuous Integration
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v1
      
    - name: Run Sonarcloud scanner
      uses: mathrix-education/sonar-scanner@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: 4.2.0.1873
        scan: true
        args: -Dsonar.projectKey=ArwynFr_AspectNetSharp -Dsonar.organization=arwynfr -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        
    - uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Compile solution
      run: msbuild AspectNetSharp.sln
